### ISSUE TITLE
Gecko integration broken after Home Assistant patch

### ISSUE THREAD

**Issue by grosa1973** [gazoodle/gecko-home-assistant#110]
Home assistant:
 Core 2024.7.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

Gecko 0.1.9

Log:
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 8:02:44 PM (3 occurrences)
Last logged: 8:02:51 PM
Unable to install package geckolib==0.4.8: WARNING: Ignoring version 0.4.8 of geckolib since it has invalid metadata: Requested geckolib==0.4.8 from https://files.pythonhosted.org/packages/95/b5/6b1293493ddbcef8c576a68adf05cdcc40b9387619507179d3b4607beabd/geckolib-0.4.8-py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier python-version (>="3.7") ~^ Please use pip<24.1 if you need to use this version. ERROR: Could not find a version that satisfies the requirement geckolib==0.4.8 (from versions: 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.3.20, 0.3.22, 0.3.23, 0.3.24, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.15) ERROR: No matching distribution found for geckolib==0.4.8

**Comment by petteram** [comment]
I have problems too! 
I have tried with HA core 2024.7.4 and 2024.7.3 
I have tried to reinstall the Gecko integration.
No success!

This is what I read in the logfiles
ogger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 10:38:43 (3 occurrences)
Last logged: 10:38:43

Detected blocking call to import_module with args ('geckolib.driver.packs.inyt',) in /usr/local/lib/python3.12/site-packages/geckolib/async_spa.py, line 270: GeckoPack = importlib.import_module(pack_module_name).GeckoPack inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 543, in _sequence_pump await self.async_connect(self._spa_identifier, self._spa_address) File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 334, in async_connect return await self.async_connect_to_spa(spa_descriptors[0]) File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa_manager.py", line 300, in async_connect_to_spa await self._spa.connect() File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 367, in connect await self._connect() File "/usr/local/lib/python3.12/site-packages/geckolib/async_spa.py", line 270, in _connect GeckoPack = importlib.import_module(pack_module_name).GeckoPack

Is this due to a intouch 2 update?

**Comment by raa-hasel** [comment]
hmm, i am on 2024.7.4 too, but gecko is running with his bugs
First installation was 2-3 month ago

Question
is gecko death, because there are no response here since ???

**Comment by malansk** [comment]
I am on 2024.7.3 with Gecko Integration working good, I use it every day to read values & send commands to my pool.
I do however also have the above mentioned warnings in the HA Core log.
Can't comment if it would be able to install on a fresh system since I use it already since 12/2023.

**Comment by raa-hasel** [comment]
as i wrote i am on 2024.7.4 (HA) and Gecko 0.1.11
sometimes the connection struggle, but after "Deactivate" Reboot and "Activate" the integration are working.

**Comment by petteram** [comment]
Solved! 
I have tried many things... reinstall gecko, removed and added device, restored an old backup. Nothing helped. I started to have a look in the in.touch2 app and noticed that the spa bath did not have any profile selected( economy, standard, away) I enabled standard mode and then it all worked fine. I am sorry for bothering you guys, but I started to get frustrated.

**Comment by ryanelliottsmith** [comment]
For the original reported issue:
```
Unable to install package geckolib==0.4.8: WARNING: Ignoring version 0.4.8 of geckolib since it has invalid metadata: Requested geckolib==0.4.8 from https://files.pythonhosted.org/packages/95/b5/6b1293493ddbcef8c576a68adf05cdcc40b9387619507179d3b4607beabd/geckolib-0.4.8-py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier python-version (>="3.7") ~^ Please use pip<24.1 if you need to use this version. ERROR: Could not find a version that satisfies the requirement geckolib==0.4.8 (from versions: 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.3.20, 0.3.22, 0.3.23, 0.3.24, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.15) ERROR: No matching distribution found for geckolib==0.4.8
```

This appears fixed in the latest version of this addon(v0.1.11)

**Comment by Wagenfeld** [comment]
Any news to this issue?

**Comment by m2kw6s** [comment]
> Solved! I have tried many things... reinstall gecko, removed and added device, restored an old backup. Nothing helped. I started to have a look in the in.touch2 app and noticed that the spa bath did not have any profile selected( economy, standard, away) I enabled standard mode and then it all worked fine. I am sorry for bothering you guys, but I started to get frustrated.

Mine broke too, but after Disabling the Gecko Integration, restarting HA, and re-enabling the integration, everything was back to normal. (HA 2024.8.3)

**Comment by aug0211** [comment]
2024.10.3 and seeing this issue. Disable/restart/enable/restart does not seem to resolve this issue.

Any tips?

**Comment by gazoodle** [comment]
Should be fixed in v0.1.13
